# Generated by Django 3.1.2 on 2022-04-07 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20220407_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='likes',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='uuid',
            new_name='id',
        ),
    ]
